### ISSUE TITLE
Feature request to specify where to move task when merging pull request

### ISSUE THREAD

**Issue by gabrieledcjr** [valerauko/wrike-ist#15]
First, thank you for this github action. Very useful!!!

Any plans on adding the option to specify where to move that task. Instead of moving a task to `Done` when merging, can we specify a different column like `Review` or `Test`.

**Comment by valerauko** [comment]
It's definitely possible, but I don't know if it's possible in an user-friendly way. Would you imagine specifying the target column by name?

**Comment by gabrieledcjr** [comment]
yes, target column by name

**Comment by valerauko** [comment]
I'll see if it can be done and update this ticket as appropriate

**Comment by valerauko** [comment]
@gabrieledcjr added this feature to the latest release. Check it out and let me know if (or not) it's as you wanted
