### ISSUE TITLE
optional state for opened, etc.

### ISSUE THREAD

**Issue by belm0** [valerauko/wrike-ist#22]
1. on PR `opened`, allow optional status change (e.g. "Team review")
2. I'd like a way to disable existing `merged` and `closed` transitions, such as by specifying empty string or "none".  Rationale:
    * wrike tasks may involve multiple PR's, so transition on merge often isn't appropriate
    * a closed PR may represent a misstep, and another will be opened in its place, so often not appropriate to cancel wrike task

Thank you for the tool!

**Comment by valerauko** [comment]
I'll take a look at this. Considering https://github.com/valerauko/wrike-ist/issues/15 is already done, it shouldn't be too difficult to implement.

**Comment by valerauko** [comment]
Since both of these require bigger changes to the code I'll split this issue into two.
