### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by jgwinner** [valerauko/wrike-ist#6]
This app looks great! 

However, I'm getting an error once I figured out the right tag for version (the README says V1 but it's currently v0.1.0)

```
Run valerauko/wrike-ist@v0.1.0
  env:
    WRIKE_TOKEN: ***
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
Error: d.Gc is not a function

```

I know you said it's pretty experimental, would be happy to give you any other testing data. Any chance for a fix?

        == John ==

**Comment by valerauko** [comment]
thanks for the report! lemme take a look, gonna fix asap!

**Comment by jgwinner** [comment]
It's weird, I didn't see the d.Gc in the Clojure code (which I don't really know, but I can sort of read it), it seems to be in the standard transpiling stuff. 

Looks weird! I don't envy you.

**Comment by valerauko** [comment]
@jgwinner pushed v1.0 which should fix both the error above and the version mismatch with the README. Can you confirm if it works for you too?

**Comment by valerauko** [comment]
Using current released version in an enterprise org, works here. Yell at me if you still have problems

**Comment by jgwinner** [comment]
Sure! WIll do, Thanks for the fast response. Got pulled off and on a couple of other things. Should have a chance to double-check this week.
